// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.9,
  "totalRatings": 14,
  "reviews": [
    {
      "author": "Jalal Schäfer",
      "rating": 5,
      "text": "Leckeres Essen. Preis Leistungsverhältnis sehr gut.\n\nEmpfehlenswert.",
      "time": "vor 3 Monaten"
    },
    {
      "author": "Jawad",
      "rating": 5,
      "text": "Total lecker 😋",
      "time": "vor einer Woche"
    },
    {
      "author": "Leonit Shpatollaj",
      "rating": 5,
      "text": "Super Ambiente, essen schmeckt hervorragend! Immer wieder gerne.",
      "time": "vor 3 Wochen"
    },
    {
      "author": "Lilli Sp",
      "rating": 5,
      "text": "super leckeres Essen, haben hierjetzt schon öfter bestellt und ich würde es jedem empfehlen!!",
      "time": "vor einem Monat"
    },
    {
      "author": "Tejveer Singh",
      "rating": 5,
      "text": "Köstliches Essen",
      "time": "vor 2 Monaten"
    }
  ]
};
